const experience = [
  {date:'Dec 2025 — Mar 2026', company:'Cloudesign Technology Service Private Limited', title:'SDE-2', description:'Worked on AI-based research products for content discovery, analysis and grant management, including Laravel upgrades and API development.', tech:['Laravel','PHP','PostgreSQL','REST APIs','TypeScript']},
  {date:'Mar 2024 — Nov 2025', company:'Planetcast Media Services Limited', title:'Software Engineer', description:'Developed video CMS modules for configuration, user, GeoIP and video management, with scalable frontend and backend services.', tech:['React.js','TypeScript','Laravel','Docker','BDD']},
  {date:'Jan 2023 — Dec 2023', company:'Akshamaala Solutions Pvt. Ltd. (Unnati)', title:'Software Engineer', description:'Built ERP workflows and API integrations for financial and verification services, supported by Laravel scheduling and automation.', tech:['Laravel','PHP','MySQL','REST APIs','Docker']},
  {date:'Dec 2021 — Jan 2023', company:'Pythonist India Pvt. Ltd.', title:'Full Stack Web Developer', description:'Contributed to e-commerce, POS, CRM and school management products, alongside hosting, server operations and deployment workflows.', tech:['Laravel','MySQL','AWS','CI/CD','JavaScript']}
];
const skills = [
  {name:'Backend', items:['PHP','Laravel','Node.js','Express.js','REST APIs']}, {name:'Frontend', items:['React.js','Vue.js','JavaScript','TypeScript','HTML','CSS']}, {name:'Database', items:['MySQL','PostgreSQL','Redis','Elasticsearch']}, {name:'DevOps & Cloud', items:['Docker','AWS','CI/CD','Git','GitHub Actions']}, {name:'Architecture', items:['MVC','OOP','Repository Pattern','Microservices','BDD / TDD']}
];
const projects = [
  {id:'aitech', featured:true, name:'AITECH', type:'Multivendor E-commerce Platform', image:'img/aitech.png', description:'Marketplace platform with dedicated customer, seller and administrator workflows.', contribution:'Built the backend and REST APIs; integrated payment gateways, shipping providers and social login.', approach:'Laravel and MySQL services supporting authentication, marketplace workflows and third-party integrations.', tech:['Laravel','Vue.js','MySQL','REST APIs','AWS','CI/CD'], filters:['Laravel','E-commerce'], url:'https://aitech.com.sa'},
  {id:'media-manager', featured:true, name:'Media Manager', type:'Video Content Management System', image:'img/mm.png', description:'A video CMS for managing configurations, videos, users, GeoIP and EPG workflows.', contribution:'Developed frontend components and Laravel backend services, including configuration and version management.', approach:'React and Laravel services backed by MySQL, Redis and containerised development workflows.', tech:['React.js','TypeScript','Laravel','MySQL','Redis','Docker'], filters:['Laravel','React','Enterprise'], url:'https://media-manager.demo.switch.tv/'},
  {id:'gms', featured:true, name:'GMS', type:'Grant Management System', image:'img/gms.png', description:'Grant management system supporting publisher workflows.', contribution:'Developed APIs and contributed to Laravel upgrades for the platform.', approach:'Laravel API services with PostgreSQL and Docker-based workflows.', tech:['Laravel','TypeScript','PostgreSQL','Docker','REST APIs'], filters:['Laravel','Enterprise'], url:'https://aisolutions.cactusglobal.com/gms/'},
  {id:'ora-finance', featured:true, name:'Ora Finance', type:'Loan Management System', image:'img/orafinance.png', description:'Financial management ERP for loan and business workflows.', contribution:'Developed a substantial portion of the system, including permissions, dynamic menus and backend API integrations.', approach:'Laravel services with React interfaces and secure third-party financial integrations.', tech:['Laravel','React.js','TypeScript','MySQL','Docker','CI/CD'], filters:['Laravel','React','ERP','Enterprise'], url:'https://los.orafinance.in'},
  {id:'royaltechno', featured:true, name:'RoyalTechno School ERP', type:'School Management ERP', image:'img/royaltechno.png', description:'A management system for student, teacher, fee and expense workflows.', contribution:'Built business modules across school management processes.', approach:'Laravel application using JavaScript and AJAX for operational workflows.', tech:['Laravel','PHP','JavaScript','AJAX'], filters:['Laravel','ERP'], url:'https://admin.royaltechnoschool.com'},
  {id:'megamart', featured:true, name:'Megamart', type:'E-commerce Platform', image:'img/megamart.png', description:'Full-stack e-commerce platform for digital shopping workflows.', contribution:'Contributed across the full-stack application and its management workflows.', approach:'Laravel and MySQL application with JavaScript-enhanced interfaces.', tech:['Laravel','PHP','JavaScript','MySQL'], filters:['Laravel','E-commerce'], url:'https://megamart.pythonistindia.com'},
  {id:'ai-solutions', name:'AI Solutions', type:'Enterprise AI Platform', image:'img/aisolutions.png', description:'AI solutions for publishers, funders and corporates.', contribution:'Developed AI features and supported API migration work.', approach:'React and Laravel application with PostgreSQL-backed API services.', tech:['React.js','TypeScript','Laravel','PostgreSQL'], filters:['Laravel','React','Enterprise'], url:'https://aisolutions.cactusglobal.com/dashboard/'},
  {id:'r-discovery', name:'R Discovery', type:'Research Assistant', image:'img/discovery.png', description:'AI research assistant for content discovery and literature review.', contribution:'Enhanced feed recommendation APIs and supported a Laravel upgrade.', approach:'Laravel and PostgreSQL application serving research content workflows.', tech:['Laravel','PHP','PostgreSQL','REST APIs'], filters:['Laravel','Enterprise'], url:'https://discovery.researcher.life/'},
  {id:'unnati', name:'Unnati ERP', type:'Agritech ERP', image:'img/unnati.png', description:'Agritech software management platform.', contribution:'Implemented operational ERP modules and Oracle system integrations.', approach:'PHP and MySQL platform with Vue.js, AJAX and third-party API integrations.', tech:['PHP','Vue.js','MySQL','AJAX','REST APIs'], filters:['ERP'], url:'https://unnati.world/shop/admin/index.php?route=common/login'},
  {id:'bajar247', name:'Bajar247', type:'Multivendor E-commerce', image:'img/bajar247.png', description:'Multivendor e-commerce platform.', contribution:'Contributed to the Laravel commerce application.', approach:'Laravel and MySQL application with JavaScript interface workflows.', tech:['Laravel','JavaScript','MySQL'], filters:['Laravel','E-commerce'], url:'https://bajar247.com/'},
  {id:'pos', name:'POS System', type:'Point of Sale', image:'img/pos.png', description:'Stock and billing management application.', contribution:'Contributed to inventory and billing workflows.', approach:'Laravel application using JavaScript and MySQL.', tech:['Laravel','JavaScript','MySQL'], filters:['Laravel','ERP'], url:'https://pos.sellbii.com/'},
  {id:'synergy', name:'Synergy ERP', type:'Business ERP', image:'img/synergy.jpg', description:'Client and agreement management ERP.', contribution:'Contributed to client and agreement management workflows.', approach:'Laravel, JavaScript, jQuery and MySQL based ERP.', tech:['Laravel','JavaScript','jQuery','MySQL'], filters:['Laravel','ERP','Enterprise'], url:'https://synergy.msell.in/'},
  {id:'little-diva', name:'Little Diva', type:'E-commerce', image:'img/littlediva.png', description:'Children’s clothing e-commerce site.', contribution:'Contributed to e-commerce workflows and interfaces.', approach:'Laravel and MySQL commerce application.', tech:['Laravel','JavaScript','MySQL'], filters:['Laravel','E-commerce'], url:'https://littlediva.in/'}
];
