const experience = [
  {date:'Dec 2025 — Mar 2026', company:'Cloudesign Technology Service Private Limited', title:'SDE-2', description:'Worked on AI research products for content discovery, analysis and grant management. Developed 100+ Nest.js APIs for GMS and built features including chat-with-PDF, PDF-to-audio and AI review.', tech:['Nest.js','Next.js','TypeScript','PostgreSQL','RAG']},
  {date:'Mar 2024 — Nov 2025', company:'Planetcast Media Services Limited', title:'Software Engineer', description:'Developed React and Node.js services for a video CMS, including GeoIP, EPG, user and video management. Added configuration rollback, version history and Redis-backed synchronization.', tech:['React.js','Node.js','TypeScript','MySQL','Redis','Cucumber.js']},
  {date:'Jan 2023 — Dec 2023', company:'Akshamaala Solutions Pvt. Ltd. (Unnati)', title:'Software Engineer', description:'Developed and maintained 100+ REST APIs with JWT and API-key authentication, integrated NetSuite and verification services, and automated transaction updates and reminders.', tech:['Node.js','Express.js','React.js','MongoDB','REST APIs','Docker']},
  {date:'Dec 2021 — Jan 2023', company:'Pythonist India Pvt. Ltd.', title:'MERN Developer', description:'Contributed to e-commerce, matrimonial, POS, CRM and school management products. Built the Aitech backend with 300+ APIs and managed AWS hosting and CI/CD delivery.', tech:['Node.js','Express.js','React.js','MySQL','AWS','GitHub Actions']}
];
const skills = [
  {name:'Languages & Frameworks', items:['JavaScript','TypeScript','React.js','Next.js','Node.js','Express.js','Nest.js','Jest']}, {name:'Frontend', items:['React.js','Next.js','TypeScript','HTML','CSS']}, {name:'Database', items:['MySQL','PostgreSQL','MongoDB','Redis','Elasticsearch']}, {name:'APIs & Architecture', items:['REST APIs','GraphQL','WebSockets','Microservices','Event-driven','RAG']}, {name:'DevOps & Tools', items:['Docker','AWS','Linux','Git','CI/CD','GitHub Actions','Swagger','Jira']}
];
const projects = [
  {id:'aitech', featured:true, name:'AITECH', type:'Multivendor E-commerce Platform', image:'img/aitech.png', description:'Marketplace platform with dedicated customer, seller and administrator workflows.', contribution:'Designed and developed the backend with 300+ APIs, payment and shipping integrations, and social login.', approach:'Node.js and Express.js services with React.js, MySQL, AWS EC2, RDS and GitHub Actions.', tech:['React.js','Node.js','Express.js','MySQL','AWS','CI/CD'], filters:['Node.js','React','E-commerce'], url:'https://aitech.com.sa'},
  {id:'media-manager', featured:true, name:'Media Manager', type:'Video Content Management System', image:'img/mm.png', description:'A video CMS for managing configurations, videos, users, GeoIP and EPG workflows.', contribution:'Developed REST APIs and React frontend modules, including configuration version history and data synchronization.', approach:'React and Node.js services backed by MySQL, Redis, Docker and Cucumber.js.', tech:['React.js','Node.js','TypeScript','MySQL','Redis','Docker'], filters:['Node.js','React','Enterprise'], url:'https://media-manager.demo.switch.tv/'},
  {id:'gms', featured:true, name:'GMS', type:'Grant Management System', image:'img/gms.png', description:'Grant management system supporting publisher and funder workflows.', contribution:'Developed 100+ APIs and AI-assisted features for grant management and research workflows.', approach:'Nest.js and Next.js services with PostgreSQL, REST APIs and RAG-based AI features.', tech:['Nest.js','Next.js','TypeScript','PostgreSQL','REST APIs'], filters:['Nest.js','Next.js','Enterprise'], url:'https://aisolutions.cactusglobal.com/gms/'},
  {id:'ora-finance', featured:true, name:'Ora Finance', type:'Loan Management System', image:'img/orafinance.png', description:'Financial management platform for loan applications, approvals, disbursements and repayments.', contribution:'Developed backend services and role-based authorization and permissions modules.', approach:'Node.js and Express.js APIs with React interfaces, MySQL, Docker and third-party integrations.', tech:['React.js','Node.js','Express.js','MySQL','Docker','CI/CD'], filters:['Node.js','React','ERP','Enterprise'], url:'https://los.orafinance.in'},
  {id:'royaltechno', featured:true, name:'RoyalTechno School ERP', type:'School Management ERP', image:'img/royaltechno.png', description:'A management system for student, teacher, fee and expense workflows.', contribution:'Built business modules across school management processes.', approach:'JavaScript application with REST APIs and database-backed operational workflows.', tech:['JavaScript','REST APIs','MySQL'], filters:['ERP'], url:'https://admin.royaltechnoschool.com'},
  {id:'megamart', featured:true, name:'Megamart', type:'E-commerce Platform', image:'img/megamart.png', description:'Full-stack e-commerce platform for digital shopping workflows.', contribution:'Contributed across the full-stack application and its management workflows.', approach:'JavaScript and MySQL application with API-driven commerce workflows.', tech:['JavaScript','REST APIs','MySQL'], filters:['E-commerce'], url:'https://megamart.pythonistindia.com'},
  {id:'ai-solutions', name:'AI Solutions', type:'Enterprise AI Platform', image:'img/aisolutions.png', description:'AI solutions for publishers, funders and corporates.', contribution:'Migrated Next.js APIs to Nest.js and developed chat-with-PDF, PDF-to-audio and AI review features.', approach:'Next.js and Nest.js services with PostgreSQL, REST APIs and RAG-based AI tools.', tech:['Next.js','Nest.js','TypeScript','PostgreSQL','RAG'], filters:['Next.js','Nest.js','Enterprise'], url:'https://aisolutions.cactusglobal.com/dashboard/'},
  {id:'r-discovery', name:'R Discovery', type:'Research Assistant', image:'img/discovery.png', description:'AI research assistant for content discovery and literature review.', contribution:'Enhanced the daily feed recommendation API for research content discovery.', approach:'Next.js and Node.js services with PostgreSQL, Elasticsearch, REST APIs and AWS.', tech:['Next.js','Node.js','TypeScript','PostgreSQL','Elasticsearch'], filters:['Next.js','Node.js','Enterprise'], url:'https://discovery.researcher.life/'},
  {id:'unnati', name:'Unnati ERP', type:'Agritech ERP', image:'img/unnati.png', description:'Agritech software management platform.', contribution:'Implemented backend APIs for supplier, store and customer management, sales, purchases and reporting.', approach:'Node.js and Express.js services with React, MongoDB and third-party API integrations.', tech:['React.js','Node.js','Express.js','MongoDB','REST APIs'], filters:['Node.js','React','ERP'], url:'https://unnati.world/'},
  {id:'bajar247', name:'Bajar247', type:'Multivendor E-commerce', image:'img/bajar247.png', description:'Multivendor e-commerce platform.', contribution:'Contributed to commerce workflows and API-driven interfaces.', approach:'JavaScript and MySQL application with REST API integrations.', tech:['JavaScript','REST APIs','MySQL'], filters:['E-commerce'], url:'https://bajar247.com/'},
  {id:'pos', name:'POS System', type:'Point of Sale', image:'img/pos.png', description:'Stock and billing management application.', contribution:'Contributed to inventory and billing workflows.', approach:'JavaScript and MySQL application with API-backed operational workflows.', tech:['JavaScript','REST APIs','MySQL'], filters:['ERP'], url:'https://pos.sellbii.com/'},
  {id:'synergy', name:'Synergy ERP', type:'Business ERP', image:'img/synergy.jpg', description:'Client and agreement management ERP.', contribution:'Contributed to client and agreement management workflows.', approach:'JavaScript and MySQL business application.', tech:['JavaScript','MySQL','REST APIs'], filters:['ERP','Enterprise'], url:'https://synergy.msell.in/'},
  {id:'little-diva', name:'Little Diva', type:'E-commerce', image:'img/littlediva.png', description:'Children’s clothing e-commerce site.', contribution:'Contributed to e-commerce workflows and interfaces.', approach:'JavaScript and MySQL commerce application.', tech:['JavaScript','MySQL','REST APIs'], filters:['E-commerce'], url:'https://littlediva.in/'}
];
